### ISSUE TITLE
To make Train.csv and Test.csv files from data folder

### ISSUE THREAD

**Issue by Maurya69** [iiitv/Movie-Review#2]
Write Function to make train.csv and test.csv in make_csv.py. Your csv files should have two columns:
First Column named 'reviews' : Should contain the review
Second Column named 'Sentiment' : Should contain sentiment '1' if positive , '0' if negative

**Comment by sharayuanuse** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by srirangamuc** [comment]
Hello Sir, I would like to contribute on this issue. Can you please assign me this issue?

**Comment by Harini-01** [comment]
Hello @Maurya69 , I would like to work on this issue. Can you assign it to me?

**Comment by AnujSaha0111** [comment]
Hello @Maurya69 Sir! I want to work on this issue

**Comment by AnujSaha0111** [comment]
Hello @Maurya69 Sir ! I want to work on the issue. Can you assign it to me?

**Comment by Maurya69** [comment]
Hey all, Your issues will be assigned on two conditions:
1. You must be from IIIT Vadodara.
2. You must write the apporach in which you are going to solve the issues.
Sorry for the delayed response. 
And new issues will be added soon maybe by tommorow so be ready.

**Comment by AnujSaha0111** [comment]
@Maurya69 Sir, I am a student of IIIT Vadodara.

**Comment by realmCode** [comment]
Solved in PR #4

**Comment by JeetJani-11** [comment]
Solved in #4
